---
driver:
  network:
  - ["private_network", {ip: "192.168.33.48"}]
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[stackengine::default]
    attributes:
